---
- name: Check EC2 tags (run on the EC2 node itself)
  hosts: 10.2.2.135
  gather_facts: yes
  vars:
    aws_region: "us-east-1"
    required_tags:
      - owner
      - environment
      - cost_center

  tasks:
    - name: Get instance-id from metadata
      ansible.builtin.shell: curl -s http://169.254.169.254/latest/meta-data/instance-id
      register: instance_id
      changed_when: false

    - name: Ensure aws CLI is present (RedHat)
      ansible.builtin.yum:
        name: awscli
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Ensure aws CLI is present (Debian)
      ansible.builtin.apt:
        name: awscli
        state: present
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: Get tags for this EC2 instance
      ansible.builtin.command: >
        aws ec2 describe-tags --filters "Name=resource-id,Values={{ instance_id.stdout }}" --region {{ aws_region }} --output json
      register: tag_output
      changed_when: false
      failed_when: tag_output.rc != 0

    - name: Parse tag names
      set_fact:
        tag_names: "{{ tag_output.stdout | from_json | json_query('Tags[].Key') }}"

    - name: Report compliance
      ansible.builtin.debug:
        msg: >-
          Instance={{ instance_id.stdout }}
          Missing={{ required_tags | difference(tag_names) }}
          Status={{ 'Compliant' if (required_tags | difference(tag_names) | length) == 0 else 'Non-compliant' }}
