---
- name: Check EC2 tags for single host (run on control node)
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "us-east-1"
    required_tags:
      - owner
      - environment
      - cost_center

  tasks:
    - name: Describe instance by private IP
      ansible.builtin.command: >
        aws ec2 describe-instances
        --region {{ aws_region }}
        --filters "Name=private-ip-address,Values=10.2.2.135"
        --query "Reservations[].Instances[]"
        --output json
      register: inst_desc
      changed_when: false

    - name: Fail if no instance found or AWS CLI error
      ansible.builtin.fail:
        msg: "No instance found or aws CLI error: {{ inst_desc.stderr | default('') }}"
      when: inst_desc.rc != 0 or (inst_desc.stdout | default('[]') | from_json | length == 0)

    - name: Extract tag keys
      set_fact:
        tag_keys: "{{ (inst_desc.stdout | from_json)[0].Tags | default([]) | map(attribute='Key') | list }}"

    - name: Compute missing tags
      set_fact:
        missing_tags: "{{ required_tags | difference(tag_keys) }}"

    - name: Show result
      ansible.builtin.debug:
        msg: "Instance i={{ (inst_desc.stdout | from_json)[0].InstanceId }} Missing={{ missing_tags }} Status={{ 'Compliant' if missing_tags|length == 0 else 'Non-compliant' }}"
