---
- name: Quick EC2 tag check (local test)
  hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars:
    aws_region: "us-east-1"
    instance_id: "i-0849caa4ca5955163"
    required_tags:
      - owner
      - environment
      - cost_center

  tasks:
    - name: Get tag keys for this instance
      ansible.builtin.command: >
        aws ec2 describe-tags
        --region {{ aws_region }}
        --filters "Name=resource-id,Values={{ instance_id }}"
        --query "Tags[].Key"
        --output text
      register: tag_keys
      changed_when: false
      failed_when: tag_keys.rc != 0 and "'UnauthorizedOperation'" not in tag_keys.stderr

    - name: Handle unauthorized operation error
      ansible.builtin.fail:
        msg: "❌ Unauthorized: AWS user/role has no permission for ec2:DescribeTags. Check IAM policy."
      when: "'UnauthorizedOperation' in tag_keys.stderr"

    - name: Compute missing tags
      ansible.builtin.set_fact:
        missing: "{{ required_tags | difference(tag_keys.stdout.split()) }}"

    - name: Show result
      ansible.builtin.debug:
        msg: "✅ Instance={{ instance_id }} | Missing={{ missing }} | Status={{ 'Compliant' if missing|length == 0 else 'Non-compliant' }}"
