---
- name: Debug incoming events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Log all events
      condition: true
      action:
        run_job_template:
          name: debug-template
          organization: Default
