---
- name: Provision RHEL Sandbox in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_type: t3.micro
    key_name: aap-kp
    region: us-east-1
    security_group: default
    subnet_id: subnet-xxxxxx     # Replace with real subnet
    image_id: ami-xxxxxxxx       # Replace with valid RHEL AMI

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "rhel-sandbox"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        wait: yes
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
      register: ec2

    - name: Show instance details
      debug:
        var: ec2

    - name: Add new instance to inventory
      add_host:
        name: "{{ ec2.instances[0].public_ip_address }}"
        groups: rhel_sandbox
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/Downloads/aap-kp.pem"

# Second play → configure the new instance
- name: Configure Sandbox
  hosts: rhel_sandbox
  become: yes
  tasks:
    - name: Install developer tools
      yum:
        name:
          - git
          - python3
          - docker
        state: present

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create marker file
      copy:
        dest: /etc/sandbox_info.txt
        content: |
          Sandbox provisioned via AAP on {{ ansible_date_time.iso8601 }}
