---
- name: Provision sandbox VM and install dev tools
  hosts: localhost
  gather_facts: false
  vars:
    region: us-east-1
    instance_type: "{{ instance_type | default('t3.medium') }}"
    ami: "{{ ami | default('ami-0abcdef1234567890') }}"   # replace with valid AMI
    key_name: "{{ key_name | default('my-ssh-key') }}"
    security_group: "{{ security_group | default('sg-xxxx') }}"
    subnet_id: "{{ subnet_id | default(omit) }}"
    tags:
      Name: "sandbox-{{ requested_by | default('dev') }}-{{ lookup('pipe','date +%s') }}"
    tools:
      - git
      - python3
      - docker
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ tags.Name }}"
        state: present
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        tags: "{{ tags }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        wait: yes
      register: ec2

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        timeout: 300

    - name: Add new host to dynamic group
      add_host:
        name: "{{ ec2.instances[0].public_ip_address }}"
        groups: provisioned_sandbox
        ansible_user: ec2-user   # adjust per AMI
        ansible_ssh_private_key_file: "{{ lookup('env','HOME') + '/.ssh/' + key_name + '.pem' }}" # optional in ad-hoc runs

- name: Configure sandbox (run against provisioned host)
  hosts: provisioned_sandbox
  become: true
  tasks:
    - name: Install dev tools (RHEL example)
      package:
        name: "{{ tools }}"
        state: present

    - name: Ensure docker enabled and started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create a marker file
      copy:
        dest: /etc/sandbox_info.txt
        content: |
          Sandbox created by {{ requested_by }} on {{ ansible_date_time.iso8601 }}
          Tools: {{ tools | join(', ') }}
